_target_: source.networks.Warper3DGS

verbose: True
viewpoint_stack: !!null
sh_degree: 3

opt:
  iterations: 30000
  position_lr_init: 0.00016
  position_lr_final: 1.6e-06
  position_lr_delay_mult: 0.01
  position_lr_max_steps: 30000
  feature_lr: 0.0025
  opacity_lr: 0.025
  scaling_lr: 0.005
  rotation_lr: 0.001
  percent_dense: 0.01
  lambda_dssim: 0.2
  densification_interval: 100
  opacity_reset_interval: 30000
  densify_from_iter: 500
  densify_until_iter: 15000
  densify_grad_threshold: 0.0002
  scale_loss_weight: 100.0
  scale_min_thresh: 0.0015  # 最小高斯尺寸（避免尖刺）
  scale_max_thresh: 0.065   # 最大高斯尺寸（避免膨胀）
  save_iterations: [7000, 15000, 20000, 26000, 30000]
  batch_size: 64
  
  TRAIN_CAM_IDX_TO_LOG: 50
  TEST_CAM_IDX_TO_LOG: 10

  wo_image_weight: False
  single_view_weight: 0.015
  single_view_weight_from_iter: 500

  use_virtul_cam: True
  virtul_cam_prob: 0.5
  use_multi_view_trim: True
  multi_view_ncc_weight: 0.15
  multi_view_geo_weight: 0.03
  multi_view_weight_from_iter: 500
  multi_view_patch_size: 3
  multi_view_sample_num: 102400
  multi_view_pixel_noise_th: 1.0
  wo_use_geo_occ_aware: False

  opacity_cull_threshold: 0.005
  densify_abs_grad_threshold: 0.0008
  abs_split_radii2D_threshold: 20
  max_abs_split_points: 50000
  max_all_points: 6000000
  exposure_compensation: True
  random_background: False


pipe:
  convert_SHs_python: False
  compute_cov3D_python: False
  debug: False

dataset:
  densify_until_iter: 15000
  source_path:  '' #path to dataset
  model_path:  '' #path to logs
  images: images
  resolution: -1
  white_background: False
  data_device: cpu
  eval: False
  preload_img: True
  ncc_scale: 1.0
  multi_view_num: 8
  multi_view_max_angle: 30
  multi_view_min_dis: 0.01
  multi_view_max_dis: 1.5
  opacity_cull_threshold: 0.05
  w_normal_prior: normals # normals
  w_depth_prior: False 